//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Employment.Common.ApplicationMessages", typeof(ApplicationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد لینک های اضافه شده به رزومه به سقف خود رسیده است.-15.
        /// </summary>
        public static string CantAddMoreLinks {
            get {
                return ResourceManager.GetString("CantAddMoreLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز وارد شده صیحیح نمی باشد.-6.
        /// </summary>
        public static string InCurrectPassword {
            get {
                return ResourceManager.GetString("InCurrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره مبایل وارد شده اشتباه است.-5.
        /// </summary>
        public static string InvalidMobileNumber {
            get {
                return ResourceManager.GetString("InvalidMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات وارد شده صحیح نمی باشد.-8.
        /// </summary>
        public static string InvalidSignInInformation {
            get {
                return ResourceManager.GetString("InvalidSignInInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک با موفقیت به رزومه اضافه شد.-14.
        /// </summary>
        public static string LinkAddedToResume {
            get {
                return ResourceManager.GetString("LinkAddedToResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز با موفقیت ویرایش شد.-7.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات وارد شده نادرست است.-1.
        /// </summary>
        public static string PasswordIsInCurrect {
            get {
                return ResourceManager.GetString("PasswordIsInCurrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل با موفقیت ویرایش شد.-12.
        /// </summary>
        public static string ProfileEditedSuccessfuly {
            get {
                return ResourceManager.GetString("ProfileEditedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل یافت نشد.-11.
        /// </summary>
        public static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رزومه با این مشخصات یافت نشد.-13.
        /// </summary>
        public static string ResumeNotFound {
            get {
                return ResourceManager.GetString("ResumeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ورود با موفقیت انجام شد.-9.
        /// </summary>
        public static string TokenCreatedSuccessfuly {
            get {
                return ResourceManager.GetString("TokenCreatedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری قبلا با این ایمیل یا نام کاربری در سایت ثبت نام کرده است.-10.
        /// </summary>
        public static string UserNameExistInDataBase {
            get {
                return ResourceManager.GetString("UserNameExistInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات وارد شده نادرست است.-2.
        /// </summary>
        public static string UserNameNotFound {
            get {
                return ResourceManager.GetString("UserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ثبت نام با موفقیت انجام شد.-3.
        /// </summary>
        public static string YouSignedUpSuccessfuly {
            get {
                return ResourceManager.GetString("YouSignedUpSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ورود با موفقیت انجام شد.-4.
        /// </summary>
        public static string YouSignInSuccessfuly {
            get {
                return ResourceManager.GetString("YouSignInSuccessfuly", resourceCulture);
            }
        }
    }
}
