//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Employment.Common.ApplicationMessages", typeof(ApplicationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد لینک های اضافه شده به رزومه به سقف خود رسیده است..
        /// </summary>
        public static string CantAddMoreLinks {
            get {
                return ResourceManager.GetString("CantAddMoreLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر اضافه شد..
        /// </summary>
        public static string CityAdded {
            get {
                return ResourceManager.GetString("CityAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر انتخاب شده برای این کشور نیست..
        /// </summary>
        public static string CityIsNotForThisCountry {
            get {
                return ResourceManager.GetString("CityIsNotForThisCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر مورد یافت نشد..
        /// </summary>
        public static string CityNotFound {
            get {
                return ResourceManager.GetString("CityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر با موفقیت ویرایش شد..
        /// </summary>
        public static string CityUpdated {
            get {
                return ResourceManager.GetString("CityUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور جدید با موفقیت ایجاد شد..
        /// </summary>
        public static string CountryAdded {
            get {
                return ResourceManager.GetString("CountryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور یافت نشد..
        /// </summary>
        public static string CountryNotFound {
            get {
                return ResourceManager.GetString("CountryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کشور ویرایش شد..
        /// </summary>
        public static string CountryUpdated {
            get {
                return ResourceManager.GetString("CountryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چنین شهری اضافه شده..
        /// </summary>
        public static string DuplicateCity {
            get {
                return ResourceManager.GetString("DuplicateCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چنین کشوری قبلا ایجاد شده..
        /// </summary>
        public static string DuplicateCountry {
            get {
                return ResourceManager.GetString("DuplicateCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتمی با این اسم قبلا ایجاد شده..
        /// </summary>
        public static string DuplicateIndustry {
            get {
                return ResourceManager.GetString("DuplicateIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چنین دسته بندی شغلی ای قبلا ایجاد شده..
        /// </summary>
        public static string DuplicateJobCategory {
            get {
                return ResourceManager.GetString("DuplicateJobCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رده سازمانی ای با این اسم قبلا ایجاد شده..
        /// </summary>
        public static string DuplicateJobSeniorityLevel {
            get {
                return ResourceManager.GetString("DuplicateJobSeniorityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته تحصیلی ای با این اسم قبلا اضافه شده..
        /// </summary>
        public static string DuplicateMajor {
            get {
                return ResourceManager.GetString("DuplicateMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استانی با این اسم قبلا ایجاد شده..
        /// </summary>
        public static string DuplicateProvince {
            get {
                return ResourceManager.GetString("DuplicateProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سابقه تحصیلی اضافه شد..
        /// </summary>
        public static string EducationHistoryAdded {
            get {
                return ResourceManager.GetString("EducationHistoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز وارد شده صیحیح نمی باشد..
        /// </summary>
        public static string InCurrectPassword {
            get {
                return ResourceManager.GetString("InCurrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمینه فعالیت شرکت اضافه شد.
        /// </summary>
        public static string IndustryAdded {
            get {
                return ResourceManager.GetString("IndustryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمینه فعالیتی یافت نشد..
        /// </summary>
        public static string IndustryNotFound {
            get {
                return ResourceManager.GetString("IndustryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمینه فعالیت ویرایش شد..
        /// </summary>
        public static string IndustryUpdated {
            get {
                return ResourceManager.GetString("IndustryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره مبایل وارد شده اشتباه است..
        /// </summary>
        public static string InvalidMobileNumber {
            get {
                return ResourceManager.GetString("InvalidMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات وارد شده صحیح نمی باشد..
        /// </summary>
        public static string InvalidSignInInformation {
            get {
                return ResourceManager.GetString("InvalidSignInInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی شغلی جدید ایجاد شد..
        /// </summary>
        public static string JobCategoryAdded {
            get {
                return ResourceManager.GetString("JobCategoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فعالیتی یافت نشد..
        /// </summary>
        public static string JobCategoryNotFound {
            get {
                return ResourceManager.GetString("JobCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی شغلی ویرایش شد..
        /// </summary>
        public static string JobCategoryUpdated {
            get {
                return ResourceManager.GetString("JobCategoryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایقه شغلی اضافه شد..
        /// </summary>
        public static string JobExperienceAdded {
            get {
                return ResourceManager.GetString("JobExperienceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سابقه شغلی یافت نشد..
        /// </summary>
        public static string JobExperienceNotFound {
            get {
                return ResourceManager.GetString("JobExperienceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رده سازمانی جدید اضافه شد..
        /// </summary>
        public static string JobSeniorityLevelAdded {
            get {
                return ResourceManager.GetString("JobSeniorityLevelAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رده سازمانی یافت نشد..
        /// </summary>
        public static string JobSeniorityLeveNotFound {
            get {
                return ResourceManager.GetString("JobSeniorityLeveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک با موفقیت به رزومه اضافه شد..
        /// </summary>
        public static string LinkAddedToResume {
            get {
                return ResourceManager.GetString("LinkAddedToResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک یافت نشد..
        /// </summary>
        public static string LinkNotFound {
            get {
                return ResourceManager.GetString("LinkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته تحصیلی با موفقیت به لیست رشته ها اضافه شد..
        /// </summary>
        public static string MajorAdded {
            get {
                return ResourceManager.GetString("MajorAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته تحصیلی یافت نشد..
        /// </summary>
        public static string MajorNotFound {
            get {
                return ResourceManager.GetString("MajorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز با موفقیت ویرایش شد..
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات وارد شده نادرست است..
        /// </summary>
        public static string PasswordIsInCurrect {
            get {
                return ResourceManager.GetString("PasswordIsInCurrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل با موفقیت ویرایش شد..
        /// </summary>
        public static string ProfileEditedSuccessfuly {
            get {
                return ResourceManager.GetString("ProfileEditedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل یافت نشد..
        /// </summary>
        public static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان جدید اضافه شد..
        /// </summary>
        public static string ProvinceAdded {
            get {
                return ResourceManager.GetString("ProvinceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان به کشور اضافه شد..
        /// </summary>
        public static string ProvinceAddedToCountry {
            get {
                return ResourceManager.GetString("ProvinceAddedToCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان یافت نشد..
        /// </summary>
        public static string ProvinceNotFound {
            get {
                return ResourceManager.GetString("ProvinceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رزومه با این مشخصات یافت نشد..
        /// </summary>
        public static string ResumeNotFound {
            get {
                return ResourceManager.GetString("ResumeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ورود با موفقیت انجام شد..
        /// </summary>
        public static string TokenCreatedSuccessfuly {
            get {
                return ResourceManager.GetString("TokenCreatedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری قبلا با این ایمیل یا نام کاربری در سایت ثبت نام کرده است..
        /// </summary>
        public static string UserNameExistInDataBase {
            get {
                return ResourceManager.GetString("UserNameExistInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات وارد شده نادرست است..
        /// </summary>
        public static string UserNameNotFound {
            get {
                return ResourceManager.GetString("UserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ثبت نام با موفقیت انجام شد..
        /// </summary>
        public static string YouSignedUpSuccessfuly {
            get {
                return ResourceManager.GetString("YouSignedUpSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ورود با موفقیت انجام شد..
        /// </summary>
        public static string YouSignInSuccessfuly {
            get {
                return ResourceManager.GetString("YouSignInSuccessfuly", resourceCulture);
            }
        }
    }
}
